column_type_map = {
    "CNPJFilial": "string",
    "CNPJEmitente": "string",
    "Razão Social Emitente": "string",
    "Chave NF-e": "string",
    "Número Protocolo": "string", # Tirar o .0
    "Número da Nota": "string",
    "Série NF": "string",
    "Valor Nota": "float64",
    "DataEmissao": "date32",
    "Data Entrada": "date32",
    "Validação SEFAZ": "string",
    "Número Item": "uint16",
    "Código Produto": "string",
    "Descrição Produto": "string",
    "Inf. Adicionais Produto": "string",
    "Quantidade": "float64", # quantidade não está batendo
    "Unidade": "string",
    "Vlr Unitário": "float64",
    "Vlr Total Item": "float64",
    "Vlr Desconto": "float64",
    "Outras Despesas Acessórias": "float64",
    "Vlr Frete": "float64",
    "CFOP": "uint16",
    "EAN Trib": "string",
    "EAN": "string",
    "CEST": "string", # string sem ponto
    "NCM": "string",
    "BC ICMS": "float64",
    "% ICMS": "float64",
    "Valor ICMS": "float64",
    "BC ICMS ST": "float64",
    "Valor ICMS ST": "float64",
    "ICMS Desonerado": "float64",
    "BC IPI": "float64",
    "% IPI": "float64",
    "Valor IPI": "float64",
    "BC COFINS": "float64",
    "% COFINS": "float64",
    "Valor COFINS": "float64",
    "BC PIS": "float64",
    "% PIS": "float64",
    "Valor PIS": "float64",
    "CSON ICMS": "string",
    "CST ICMS": "string", # errado
    "CST IPI": "string", # errado
    "CST PIS": "string",
    "CST COFINS": "string",
    "UF Emitente": "string",
    "UFDestinatario": "string",
    "Estrutura Válida": "string",
    "Cód. Origem": "string", #string
    "Origem Mercadoria": "string",
    "Recebimento Físico": "string",
    "Inf. Adicionais Fisco": "string",
    "Dados Adicionais": "string",
    "Forma de Entrada": "string"
}