from worker_transmitter_notifier.src.controller.sharepoint_files_controller import SharepointFilesController


sharepoint_files_controller = SharepointFilesController()
sharepoint_files_controller.get_files_and_send_to_rabbitmq()
